export { default as menuHamburgerIcon } from './menu-hamburger.svg'
export { default as facebookIcon } from './facebook.svg'
export { default as instagramIcon } from './instagram.svg'
export { default as linkedinIcon } from './linkedin.svg'
export { default as twitterIcon } from './twitter.svg'
export { default as youtubeIcon } from './youtube.svg'
export { default as searchOutlinedIcon } from './search-outlined.svg'
